TDFS Log: 2020/12/12 13:30:11 client.go:200: XXX Client error: Post http://localhost:11090/getReplicaLocations: dial tcp 127.0.0.1:11090: connect: connection refused
TDFS Log: 2020/12/12 13:30:27 client.go:200: XXX Client error: Post http://localhost:11090/getReplicaLocations: dial tcp 127.0.0.1:11090: connect: connection refused
TDFS Log: 2020/12/12 15:58:29 client.go:179: XXX Client error: fileName already in namespace
TDFS Log: 2020/12/12 16:14:53 client.go:165: XXX Client error: file already exist in namespace
TDFS Log: 2020/12/12 16:15:05 client.go:62: XXX Client error at GetFile, file not exist
TDFS Log: 2020/12/12 16:15:47 utils.go:32: XXX Utils error at FastWriteopen ./local-data/AFile.txt: no such file or directory
TDFS Log: 2020/12/12 16:26:38 client.go:62: XXX Client error at GetFile, file not exist
TDFS Log: 2020/12/12 16:27:19 client.go:62: XXX Client error at GetFile, file not exist
TDFS Log: 2020/12/12 18:09:26 utils.go:135: XXX Utils error at readFileByBytes(open): open BFile.txt: no such file or directory
TDFS Log: 2020/12/12 18:11:54 utils.go:135: XXX Utils error at readFileByBytes(open): open AFile.txt: no such file or directory
TDFS Log: 2020/12/12 18:13:23 client.go:170: XXX Client error: file already exist in namespace
TDFS Log: 2020/12/12 18:21:04 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:23:25 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:25:49 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:27:19 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:28:38 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:29:54 client.go:257: XXX Client error: Post http://localhost:11090/getReplicaLocations: EOF
TDFS Log: 2020/12/12 18:32:23 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:32:35 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:33:25 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/12 18:34:21 namenode.go:142: XXX NameNode error: no available datanode
TDFS Log: 2020/12/12 18:34:21 client.go:257: XXX Client error: Post http://localhost:11090/getReplicaLocations: EOF
TDFS Log: 2020/12/12 18:35:03 namenode.go:142: XXX NameNode error: no available datanode
TDFS Log: 2020/12/12 18:35:03 client.go:257: XXX Client error: Post http://localhost:11090/getReplicaLocations: EOF
TDFS Log: 2020/12/13 12:13:47 namenode.go:26: XXX NameNode error: no available datanode
TDFS Log: 2020/12/13 12:13:47 client.go:265: XXX Client error: EOF
TDFS Log: 2020/12/13 14:24:06 datanode.go:185: XXX DataNode error: unlinkat TinyDFS/DataNode3/achunkhashs: permission denied
TDFS Log: 2020/12/13 14:44:06 datanode.go:185: XXX DataNode error: unlinkat TinyDFS/DataNode3/achunkhashs: permission denied
TDFS Log: 2020/12/13 14:46:05 datanode.go:179: XXX DataNode error: mkdir TinyDFS/DataNode3: permission denied
TDFS Log: 2020/12/13 16:00:23 client.go:224: XXX Client error: Post http://datanode1:11091/putchunk: dial tcp: lookup datanode1: Temporary failure in name resolution
TDFS Log: 2020/12/13 16:44:45 client.go:224: XXX Client error: Post http://datanode3:11093/putchunk: dial tcp: lookup datanode3: Temporary failure in name resolution
TDFS Log: 2020/12/13 16:49:07 client.go:224: XXX Client error: Post http://datanode1:11091/putchunk: dial tcp 172.18.0.4:11091: connect: connection refused
TDFS Log: 2020/12/13 16:50:29 client.go:167: XXX Client error: file already exist in namespace
